version: '3.8'

services:
  truststaff:
    container_name: truststaff
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app