version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: truststaff_postgres
    restart: always
    env_file:
      - .env.postgres
    volumes:
      - truststaff_postgres_data:/var/lib/postgresql/data
    networks:
      - truststaff_network

  truststaff:
    container_name: truststaff
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - truststaff_network

volumes:
  truststaff_postgres_data:

networks:
  truststaff_network: