"""add commendation field

Revision ID: 5099e7b893f0
Revises: bef2525e7331
Create Date: 2025-05-09 21:57:46.746923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5099e7b893f0'
down_revision: Union[str, None] = 'bef2525e7331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reputationrecord', sa.Column('commendation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reputationrecord', 'commendation')
    # ### end Alembic commands ###
