"""add login attempts table

Revision ID: ca0dddc49a8c
Revises: 46dc9112b49e
Create Date: 2025-05-11 01:32:30.063274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0dddc49a8c'
down_revision: Union[str, None] = '46dc9112b49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loginattempt',
    sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(), nullable=False),
            sa.Column('ip_address', sa.String(), nullable=False),
            sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempt_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loginattempt')
    # ### end Alembic commands ###
