"""add verification status to user

Revision ID: e3d3ad535ada
Revises: 5099e7b893f0
Create Date: 2025-05-10 01:43:21.692401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d3ad535ada'
down_revision: Union[str, None] = '5099e7b893f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_status', sa.String(), nullable=False, server_default='unverified'))
    op.add_column('user', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rejection_reason')
    op.drop_column('user', 'verification_status')
    # ### end Alembic commands ###
